- src/cli/cli.cc
- src/desktop/main.cc
- src/window/apple.mm
- src/window/linux.cc
- src/window/options.hh
- src/window/win.cc
- src/window/window.hh
- ~~default title in config on mac~~
- ~~default title in config on linux~~
- ~~default title in config on windows~~
> Percent changes for initial width and height values

- src/cli/templates.hh
- src/desktop/main.cc
- src/ipc/bridge.cc
- src/ipc/ipc.hh
> add --stdin to read from stdin and emit to window 0 as an event

- src/cli/cli.cc
- src/cli/templates.hh
- src/common.hh
- src/desktop/main.cc
- src/init.cc
- src/mobile/ios.mm
This lets me use Vite in development
> feat(ios): use localhost in DEBUG mode

- src/cli/cli.cc
> fix(cli): check if `pathToProfile` exists

- .github/workflows/ci.yml
Trying to run io tests on Linux, macOS, Android Emulator and iOS Simulator
> Run io tests on CI

- src/cli/cli.cc
> improve device not found error

- src/core/core.cc
- src/ipc/bridge.cc
- src/window/win.cc
See commit comments for more info.
> Windows bridge support

- bin/uninstall.sh
`./bin/uninstall.sh` will uninstall installed files. It will honor `PREFIX` and `SOCKET_HOME` environment variables
> initial uninstall script

- npm/packages/@socketsupply/socket-darwin-arm64/package.json
- npm/packages/@socketsupply/socket-darwin-x64/package.json
- npm/packages/@socketsupply/socket-linux-x64/package.json
Includes changes: https://github.com/socketsupply/socket/compare/6ca05797f1707a02e5408854a166c0ad81f0e9f8...13a7bb98598134fa4884f48c73c8d20623e562d4
> Publish NPM Modules

- .github/workflows/ci.yml
Reverts socketsupply/socket#148
> Revert "ci: run CI against forks on pull request assign event"

- bin/install.ps1
Newer versions of cmake output to build/configuration_type Both output types now supported.
> windows/libuv: Resolve build path issue

- api/test/index.js
- package.json
- test/src/backend.js
- test/src/fs/flags.js
- test/src/fs/index.js
- test/src/fs/promises.js
- test/src/index.js
- test/src/ipc.js
- test/src/runtime.js
All the tests should run on the same tick, otherwise they don't run at all
Better review with hidden spaces: https://github.com/socketsupply/socket/pull/143/files?diff=split&w=1
> api/test: fix test runner

- api/README.md
- api/bootstrap.js
- api/ipc.js
- bin/generate-docs.js
ref https://github.com/socketsupply/sockets.sh/issues/71
> Hide bootstrap module from docs

- src/cli/cli.cc
Linux failing 👍 (core dump)
Macos passing 👍
> ci: Resolve headless params and exit code issue

- bin/build-runtime-library.sh
- bin/install.ps1
- bin/install.sh
Implement mtime checks as per `build-runtime-libraries.sh`
Implement `install.sh --force` option
Implement `install.ps1 -force` option
> install.sh: build optimisations

- api/diagnostics/channels.js
- api/diagnostics/window.js
- api/external/libsodium/index.js
- bin/install.sh
- bin/ldflags.sh
- src/android/window.cc
- src/app/app.cc
- src/cli/cli.cc
- src/common.hh
- src/core/core.hh
- src/desktop/main.cc
- src/init.cc
- src/ios/ios.mm
- src/ipc/bridge.cc
- test/src/process.js
This was a wild one, but I tried to leave as many comments as possible!
> Launch macOS application with NSWorkspace and use OSLogStore for log retrieval

- api/crypto.js
- api/crypto/sodium.js
- api/node-esm-loader.js
- bin/generate-api-import-map.sh
- src/android/webview.kt
- src/android/window.kt
- src/cli/cli.cc
- src/ipc/bridge.cc
- Drops import maps from Android as we handle the `socket:` protocol in request interception.
- Cleans up some of `api/`
- Ensure `socket/` directory copied after user build command is invoked
> Modules clean up

- api/buffer.js
- api/crypto.js
- api/ipc.js
- api/os.js
- api/process.js
- npm/bin/ssc-platform.js
- npm/bin/ssc.js
- src/app/app.cc
- src/cli/cli.cc
- src/common.hh
- src/core/core.cc
- src/core/core.hh
- src/desktop/main.cc
- src/ios/ios.mm
- src/ipc/bridge.cc
- test/scripts/test-desktop.js
- test/src/os.js
- test/src/process.js
This PR also adds a few more missing porcelain functions for `os` and `process`
> Introduce 'os.hrtime()' and 'os.availableMemory()'

- bin/build-runtime-library.sh
- bin/install.ps1
- bin/install.sh
- npm/packages/@socketsupply/socket-win32-x64/bin/install-pre-reqs.js
- npm/packages/@socketsupply/socket-win32-x64/package.json
- npm/packages/@socketsupply/socket/package.json
%comspec% call is no long required, sub process can run in the same session
(Due to the fact that install-pre-reqs will
now have access to stdin)
Requires create-socket-app@1.0.13
> socket-win32-x64: better install process

- bin/install.ps1
Resolves  HRESULT: 0x800A0035 (CTL_E_FILENOTFOUND)
> FTE: install.ps1: recheck clang++

- npm/bin/ssc.js
This code seems to be unreachable. @mribbons
> Unreachable code detected

- api/application.js
We need to be sure we are doing this everything so we can have safe interop in node
> fix(api/application.js): fix nullable check

- src/cli/cli.cc
also use one style for all the warnings and error (all capital followed by colon)
> use the same style for warnings and errors in cli

- .github/workflows/ci.yml
- api/internal/init.js
- bin/android-functions.sh
- bin/clean.sh
- bin/install.sh
- src/android/bridge.kt
- src/cli/cli.cc
- src/core/runtime-preload.hh
- test/scripts/bootstrap-android-emulator.sh
- test/scripts/poll-adb-logcat.sh
- test/scripts/test-android-emulator.sh
- test/scripts/test-android.js
- test/scripts/test-desktop.js
- test/socket.ini
- test/src/application.js
- test/src/dgram.js
- test/src/diagnostics/channels.js
- test/src/diagnostics/window.js
- test/src/test-context.js
- test/src/webview.js
...so we can be sure Socket builds. We can enable running tests on mobile later
> ci: enable Socket build

- npm/packages/@socketsupply/socket-darwin-x64/package.json
- npm/packages/@socketsupply/socket-linux-x64/package.json
- npm/packages/@socketsupply/socket-win32-x64/package.json
- npm/packages/@socketsupply/socket/package.json
Steps to publish a version:
1. `./bin/version-npm-modules.sh patch` this will bump the version for your platform
2. `./bin/publish-npm-modules.sh --only-platforms --registry https://npm.pkg.github.com` this will publish to the GH registry
3. `./bin/publish-npm-modules.sh --only-platforms` this will publish to the npm registry
4. `git commit` + `git push`
> pre-beta release

- bin/android-functions.sh
- bin/functions.sh
Resolves https://github.com/socketsupply/socket/issues/289
> android-functions.sh: don't use Android Studio's sdk manager

- bin/install.ps1
Resolves https://github.com/socketsupply/socket/issues/321
> install.ps1: fix issue when cmake installed separately

- npm/src/index.js
- src/cli/cli.cc
- src/cli/templates.hh
> Support android for 'ssc list-devices'

- npm/packages/@socketsupply/socket-darwin-arm64/package.json
- npm/packages/@socketsupply/socket-darwin-x64/package.json
- npm/packages/@socketsupply/socket-linux-x64/package.json
- npm/packages/@socketsupply/socket-win32-x64/package.json
- npm/packages/@socketsupply/socket/package.json
> NPM Pre Release

- clib.json
- npm/packages/@socketsupply/socket-darwin-arm64/package.json
- npm/packages/@socketsupply/socket-darwin-x64/package.json
- npm/packages/@socketsupply/socket-linux-arm64/package.json
- npm/packages/@socketsupply/socket-linux-x64/package.json
- npm/packages/@socketsupply/socket-win32-x64/package.json
- npm/packages/@socketsupply/socket/package.json
> Beta Release: v0.2.0

- api/dgram.js
- test/src/dgram.js
Resolves a relay connectivity issue
> dgram: don't use localhost as addr on win32

- bin/Get-VCVars.ps1
- bin/build-runtime-library.sh
- bin/functions.sh
- bin/install.ps1
- bin/install.sh
- src/cli/cli.cc
Resolves https://github.com/socketsupply/socket/issues/316
+ support spaces in clang++ path
> windows fte: Locate vcvars64.bat more reliably

- bin/android-functions.sh
- bin/install.sh
Resolves https://github.com/socketsupply/socket/issues/339
> android fte: continue building if n to android

- bin/functions.sh
- add a `git` dependency which is not pre-installed on Ubuntu
- add `dnf` which is used on Fedora by default now
> Minor FTE improvements

- api/index.d.ts
- api/stream-relay/index.js
- bin/generate-typescript-typings.sh
From a pairing session with @heapwolf
> Update stream-relay-protocol source

- bin/android-functions.sh
android fte/darwin: Don't use /usr/bin/javac
fixes https://github.com/socketsupply/socket/issues/348
> darwin / android fte: fix usr javac hang

- bin/install.sh
Resolves silent fail issue - sudo may have been masking return code.
> install.sh: check $PREFIX/bin exists

- bin/install.sh
Fixes https://github.com/socketsupply/socket/issues/379
> install.sh: don't advise sudo with brew install

- src/cli/cli.cc
> android: fix ndkbuild not occuring with -r -o

- api/peer.js
> fixing typo on 'clusterId' property

- api/README.md
- api/crypto.js
- api/external/libsodium/index.js
> Clean up useless API imports

- src/cli/cli.cc
Resolves https://github.com/socketsupply/socket/issues/395
> ssc build -r -o --platform=android - fix avdmanager + emulator code

- src/cli/cli.cc
This PR replaces part of #394 except the Android changes that we can figure out later
> Fix `ssc run` to be on par with `ssc build`

- src/cli/cli.cc
1. Detect exit code
2. Timeout if sys.boot_completed != 1 after 120s or configured timeout
Resolves https://github.com/socketsupply/socket/issues/454
> cli / android emulator: fix hang on crash

- src/cli/cli.cc
> Fix missing forwarded test file in cli

- src/cli/cli.cc
> fix(cli): make socket.ini's  work again

- bin/publish-npm-modules.sh
we need this to add to our website
see https://github.com/socketsupply/socketsupply.co/pull/241
> chore(docs): add contrubution guide to socket npm package

- src/cli/cli.cc
> fix(cli): fix `ssc list-devices` options parsing

- src/desktop/main.cc
> Notify CLI in 'shutdownHandler' for macOS

- api/README.md
- bin/generate-docs.js
Review with hidden spaces https://github.com/socketsupply/socket/pull/537/files?diff=split&w=1
Ref: https://github.com/socketsupply/socketsupply.co/issues/230
> chore(docs): add Buffer module docs

- src/common.hh
> fix(src/common.hh): set type in 'msleep' prototype

- src/cli/cli.cc
- test/scripts/test-android-emulator.sh
- test/scripts/test-android.js
- test/scripts/test-desktop.js
- test/scripts/test-ios-simulator.js
- test/src/index.html
fixes https://github.com/socketsupply/socket/issues/556
> use the `--test` option for the test app

- src/cli/cli.cc
- src/desktop/main.cc
After some experimentation with the project, I was able to get the dev server URL working on mac desktop with a few changes to cli.cc and main.cc
> desktop support for dev server ( related to #410 )

- src/android/window.cc
- src/android/window.kt
- src/cli/cli.cc
- src/cli/templates.hh
- src/ios/main.mm
This was preventing `--test=...`, etc from working
> Forward argv to 'socket.ini' and mobile

- api/config.md
- src/cli/templates.hh
> fix(src/cli/templates.hh): fix default '[webview]' config

- src/cli/cli.cc
> chore(src/cli/cli.cc): only remove 'socket/node_modules'

- api/config.md
- bin/generate-docs.js
ref: https://github.com/socketsupply/socketsupply.co/pull/259
> chore(docs): improve config doc

- api/test/index.js
Dispatch input event when typing, which simulates typing a bit more.
> Improve type test helper

- bin/publish-npm-modules.sh
We are just linking to the GitHub on a website now
> chore(npm): remove CONTRIBUTING.md from the npm package

- src/window/apple.mm
- src/window/window.hh
This should prevent incorrect usage of `NSWindow*` and `WKWebView*` when the window is closed
> Darwin Window fixes

- api/README.md
- api/crypto.js
- api/errors.js
- api/fs/dir.js
- api/fs/handle.js
- api/fs/index.js
- api/fs/promises.js
- api/index.d.ts
- api/os.js
- api/process.js
- api/test/index.js
- api/window.js
I left some comments for a further fixes
> docs: update docs

- src/desktop/main.cc
The IPC::Message constructor decodes the `value` and `seq` properties by default. If you pass true, the arguments will be decoded too.
> fix: remove superfluous decodeURIComponent calls

- npm/packages/@socketsupply/socket/package.json
In my experience, this can help tsc language server find the typings.
> chore: add exports field to @socketsupply/socket package

- npm/packages/@socketsupply/socket-node/index.js
In some cases, user-created logs may be written directly to `process.stdout` and `process.stderr` so this PR intercepts those too.
Another PR incoming that will print the Node.js logs in the main process and send them to Console.app with os_log on macOS/iOS.
> fix: send all process.stdout/process.stderr writes through ipc

- src/cli/cli.cc
- src/common.hh
- src/config.hh
- src/init.cc
> Reduce 'init.cc' header dependency

- api/CONFIG.md
- bin/docs-generator/config.js
> More docs update

- bin/android-functions.sh
I was experimenting with variables and ended up in situation where I can't update because these variables are present, but the directories are empty or tool is missing. This PR fixes those cases
> Improve checks in android functions

- bin/android-functions.sh
- src/cli/cli.cc
I made some search on internet and found that people started to have this error recently. Usually this is solved by just removing this component.
> chore(cli): remove patcher;v4

- api/index.d.ts
- api/stream-relay/index.js
- api/stream-relay/packets.js
- api/stream-relay/sugar.js
> improve api defaults, property check peer when offline

- .github/workflows/ci.yml
> reuse Ci build artifacts

- api/dgram.js
- api/fs/web.js
- src/core/fs.cc
- src/ipc/bridge.cc
- src/window/win.cc
- test/src/router-resolution.js
This PR fixes various tests and bugs on Windows
> Various Windows fixes

- src/core/javascript.cc
Introduce low level consolidated 'dragdropfiles' event for eventual 'dropfiles' event
> refactor(src/core/javascript.cc): 'dragdropfiles'

- api/internal/init.js
Dispatch dragdropfiles with FileSystemDirectoryHandle or FileSystemFileHandle entires in a handles array on the event.
> Add dragdropfiles event

- api/CONFIG.md
- api/README.md
- api/ipc.js
- npm/packages/@socketsupply/socket-node/README.md
- npm/packages/@socketsupply/socket-node/package.json
- src/android/internal.hh
- src/cli/templates.hh
small PR to remove any legacy copy
> update references to SDK or sockets.sh

- src/ipc/bridge.cc
> fix(src/ipc/bridge.cc): escape mount mapping keys

- api/CONFIG.md
- src/cli/cli.cc
- src/cli/templates.hh
includes a minor copy update to the ini file
> add ios nonexempt encryption default

- api/index.d.ts
- api/path/index.js
- api/path/well-known.js
This provides a shortcut to the correct home folder, be it the real home folder or the one in the sandbox container.
> Add HOME to the well know path list

- npm/bin/ssc-platform.js
- npm/bin/ssc.js
- src/cli/cli.cc
- src/core/core.cc
- src/core/core.hh
- src/core/file_system_watcher.cc
- src/core/file_system_watcher.hh
- src/core/fs.cc
- src/desktop/main.cc
- src/ipc/bridge.cc
- src/process/process.hh
This PR addresses the internal implementation of the `FileSystemWatcher` class by replacing a custom event loop implementation with one provided by `SSC::Core`
> Fix `FileSystemWatcher` high CPU

- api/index.d.ts
- package.json
closes https://github.com/socketsupply/socket/issues/784
> chore(package.json): update to TypeScript 5.3

- bin/docs-generator/api-module.js
- bin/generate-docs.js
make the URLs correct on both Unix and Windows
> chore(docs): fix API URls

- src/cli/cli.cc
fixes incorrect property string
> fix env property

- bin/android-functions.sh
- bin/functions.sh
- npm/src/index.js
This PR reduces logging verbosity for android and improves detection when to setup build dependencies for android. The `npm` script will no longer attempt to just use sudo without requesting it with cleaner DX
> Reduce FTE noise

- api/hooks.js
Note this is a PR against the `[application-url-hook](https://github.com/socketsupply/socket/tree/application-url-hook)` branch.
> Implement JS handler for ApplicationURLEvent

- src/cli/cli.cc
- src/cli/templates.hh
> refactor(cli): make '[android] icon' optional

- src/core/bluetooth.cc
- src/ipc/bridge.cc
> Enable bluetooth on demand guarded by permissions

- api/CONFIG.md
- src/android/main.kt
- src/android/runtime.cc
- src/android/webview.kt
- src/android/window.kt
- src/app/app.cc
- src/app/app.hh
- src/cli/cli.cc
- src/cli/templates.hh
- src/core/ini.cc
- src/core/preload.cc
- src/ios/main.mm
- src/ipc/bridge.cc
- src/window/apple.mm
- src/window/linux.cc
- src/window/win.cc
Closes #871 
This enables setting custom HTTP headers for all navigator requests where
```ini
[webview]
headers[] = "X-Custom-Header: some-value"
```
will be made available in all requests made in the webview.
> Custom webview headers and applinks

- api/README.md
- api/index.d.ts
- api/window.js
- src/desktop/main.cc
- src/window/apple.mm
- src/window/linux.cc
- src/window/win.cc
- src/window/window.hh
adds `window.maximize()`, `window.minimize()`, and `window.restore()` methods.
> Window methods

- api/README.md
- api/application.js
- api/index.d.ts
- src/desktop/main.cc
- src/window/apple.mm
- src/window/linux.cc
- src/window/options.hh
- src/window/win.cc
- src/window/window.hh
adds an `aspectRatio` property of type string (split on `:`), providing two float values which set the window's aspect ratio.
> feature(window): add ability to specify window asepct ratio

- api/CONFIG.md
- api/README.md
- api/application.js
- api/index.d.ts
- api/internal/permissions.js
- api/service-worker/container.js
- api/window.js
- src/cli/cli.cc
- src/cli/templates.hh
- src/core/child_process.cc
- src/core/core.hh
- src/core/platform.cc
- src/core/service_worker_container.cc
- src/core/service_worker_container.hh
- src/desktop/main.cc
- src/ipc/bridge.cc
- src/process/win.cc
- src/window/apple.mm
- src/window/linux.cc
- src/window/options.hh
- src/window/win.cc
- src/window/window.hh
> Window features

- src/desktop/main.cc
- src/window/apple.mm
- src/window/linux.cc
- src/window/win.cc
- src/window/window.hh
> Window improvements
