socketsupply/socket

- bin/install.sh
On a fresh install of `socket` on macOS / Darwin (12.6), the dependency check does not properly require `automake` (rather, `make`).
Without `automake`, `install.sh` proceeds to call `./configure`, which promptly fails due to the lack of required deps.
Accordingly, this PR **properly checks for `automake` on macOS / Darwin** and dies if not present.
Similarly, as `autoconf` is the Linux equivalent, this PR moves its respective check to the Linux-specific block.
> fix(install): Fix Platform-Specific Build Tool Detection

- src/cli/cli.cc
- src/core/runtime-preload.hh
- src/desktop/main.cc
> Navigate from the frontend and backend process management

- bin/cflags.sh
- bin/install.sh
This allows debuggable builds of the Socket runtime.
```sh
DEBUG=1 bin/install.sh
```
This replaces the `-Os` flag with `-O0 -g` flags.
> fix: use -O0 and -g in `bin/install.sh` when DEBUG=1 is used

- bin/build-runtime-library.sh
⚠️ Only tested on Darwin
https://github.com/socketsupply/socket/commit/178580d65f733c1e18387c860ab5ae5ff8135177#r92242711
> fix: call `stat` correctly on Darwin

- src/cli/cli.cc
This removes the `/./` from `targetPath` variable, which was causing an error with `security` tool for reading provisioning profiles.
> fix: resolve `targetPath` correctly

- bin/install.ps1
- bin/install.sh
- src/app/app.cc
- src/app/app.hh
- src/cli/cli.cc
- src/common.hh
- src/core/core.hh
- src/desktop/main.cc
- src/init.cc
- src/process/process.hh
- src/process/unix.cc
- src/process/win.cc
- src/window/win.cc
- src/window/window.hh
This can build the tests of the `ipc-cleanup` branch in the `io` repo, but then the test runner fails hard when it attempts to execute the tests. Going to investigate if that has anything to do with `ssc` or if it's just because of the changes to the `io` repo.
Also for some reason this patch fixes 2 tests in the `io` repo's `ipc-cleanup` branch on Linux.
Side note: we might need to do something similar to ab366a5 for Linux. As far as I can see it currently also won't handle spaces in paths.
> Lots of changes for Windows

- bin/install.ps1
```
* Options added:
-debug: Do a debug build of libuv and ssc. Install libuv's pdb file for
debugging info.
-skipwebview: Skip downloading webview. User can use this if they've
already downloaded WebView2 before and are doing a rebuild.
-webview: Pass in the version of webview to download.
-uv: Pass in the tag uv will checkout. This option will not override a
previously checked out version of libuv. In the future it should be
fixed to have the install script check which tag is checked out and
do a comparison of which version is required. Then redownload and
rebuild if necessary.
* Checkout libuv at a specific tag instead of at latest v1.x branch.
* Always force the rebuild of libuv. cmake will automatically skip the
build if it's already been done in the past.
* Force copy all the files …
```
> bin: add options to Windows build script

- bin/install.sh
- src/cli/cli.cc
- src/cli/templates.hh
- src/common.hh
- src/config.cc
- src/config.hh
- src/desktop/main.cc
- src/init.cc
- src/process/process.hh
- src/process/unix.cc
- src/process/win.cc
This makes `ssc.conf` an actual program. So now its type safe. There are some other obvious upsides and escape hatches. The only requirement of the program is that is produces a variable called "config".
```c++
Config config {
.build = "node bin/build.js",
.bundle_identifier = "co.socketsupply.simulator",
.copyright = "(c) Socket Supply Co.",
.description = "A UI for visualizing Stream Relay Protocol simulations",
.env = "USER, TMPDIR, PWD",
.executable = "srv",
.flags = "-O3",
.debug = {
.flags = "-g"
},
.file_limit = 1024,
.window = {
.height = 750,
.width = 1024,
},
.lang = "en-us",
.maintainer = "Beep Boop Corp.",
.name = "srv",
.output = "dist",
.version = "0.0.1"
};
```
> typed config

- src/app/app.cc
- src/app/app.hh
- src/desktop/main.cc
- src/window/linux.cc
```
window: use unique app ptr in lambda
When shutdownHandler called from the windowManager instance (assigned as
onExit) the member variable "app" is used instead of the stack allocated
App instance.
Trying to access the member variable app after running
windowManager.destroy() causes a segfault since the reference on the
WindowManager instance is no longer valid.
To get around this assign the App instance to a static pointer variable
and use that instead.
Make the App and WindowManager instances static to simplify
initialization order and remove the possibility for a race condition.
```
```
app: don't use opaque ptr
No reason to store the WindowManager instance as an opaque pointer since
none of the member methods of WindowManager are being used. Instead
forward declare it and store the …
```
> Fix crash and remove opaque ptr

- src/cli/cli.cc
fs::path() fails when a path contains quotes. So do a partial revert of 0d72df78 and add the quotes for the compile paths inline.
> cli: don't use quotes for file paths

- src/desktop/main.cc
This should fix: `libc++abi: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument`
> fix: 'process' leak and 'killProcess' dealloc

- src/cli/cli.cc
- src/process/process.hh
- src/process/unix.cc
- src/process/win.cc
This pull request introduces `Process::wait()` to allow the caller to wait for the child process to exit with a status code. @heapwolf observed a race condition in the build step as the main process (`ssc`) was not blocking after `process->open()` was called.
> Process wait

- src/window/linux.cc
Just noticed if an error occurs, it crashes:
```js
• Welcome to the Socket Runtime (v0.1.0) REPL
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string: construction from null is not valid
Aborted (core dumped)
```
Instead I should see:
```js
• Welcome to the Socket Runtime (v0.1.0) REPL
Uncaught ReferenceError: Can't find variable: node
at from@file:///home/werle/repos/socketsupply/socket-repl/build/linux/socket-repl_v0.1.7-1_amd64/opt/socket-repl/index.js:3807:33
at @file:///home/werle/repos/socketsupply/socket-repl/build/linux/socket-repl_v0.1.7-1_amd64/opt/socket-repl/index.js:4103:37
at file:///home/werle/repos/socketsupply/socket-repl/build/linux/socket-repl_v0.1.7-1_amd64/opt/socket-repl/index.html:1:25
```
> fix early free in 'window.eval' IPC command

- bin/build-runtime-library.sh
- bin/cflags.sh
- bin/clean.sh
- bin/install.sh
- bin/ldflags.sh
- bin/publish-npm-modules.sh
- bin/version-npm-modules.sh
- npm/bin/ssc-platform.js
- npm/bin/ssc.js
- npm/bin/verify-platform.js
- npm/packages/@socketsupply/socket-darwin-arm64/package.json
- npm/packages/@socketsupply/socket-darwin-x64/package.json
- npm/packages/@socketsupply/socket-linux-arm64/package.json
- npm/packages/@socketsupply/socket-linux-x64/package.json
- npm/packages/@socketsupply/socket-win32-x64/package.json
- npm/packages/@socketsupply/socket/index.js
- npm/packages/@socketsupply/socket/package.json
- npm/src/index.js
This pull request fixes #90 and introduces NPM modules based on platform and architecture as optional dependencies to the `@socketsupply/socket` module. Currently, there is only support for `darwin` and `linux`.
The `package.json` for each module is maintained in `npm/packages/@socketsupply/*`. They should be updated manually. However, there is a connivence script for versioning all platform packages:
```sh
bin/version-npm-modules.sh <npm version args>
```
The modules can be published with a helper script `bin/publish-npm-modules.sh [--dry-run] [--only-top-level] [--only-platforms]`
Installing the top level module can be done with:
```sh
npm install -g @socketsupply/socket
```
You may need to set your global [NPM Prefix](https://docs.npmjs.com/cli/v8/commands/npm-prefix) first: …
> NPM Modules

- src/cli/cli.cc
Reverts socketsupply/socket#116
This was incorrect. We should check filename from JS at runtime
> Revert "cli: print error when test file doesn't exist"

- bin/cflags.sh
- bin/install.sh
- bin/version.sh
Minor cleanup to change using backticks in bash to use $() for command substitution.
This was the only remaining changes that hadn't already landed in https://github.com/socketsupply/socket/pull/27.
> bin: cleanup backtick usage

- src/cli/cli.cc
There was a trailing \ causing the clang++ compiler to incorrectly interpret the path.
> cli: fix build paths for clang

- npm/packages/@socketsupply/socket-darwin-arm64/package.json
- npm/packages/@socketsupply/socket-darwin-x64/package.json
- npm/packages/@socketsupply/socket/package.json
- src/android/window.cc
- src/cli/cli.cc
- src/cli/templates.hh
- src/desktop/main.cc
- src/mobile/ios.mm
- src/window/linux.cc
- src/window/win.cc
- src/window/window.hh
- test/socket.ini
- test/src/runtime.js
It's confusing to have all three: `name`, `title` and `executable`
Changes in this PR:
- previously ungrouped fields are in either `[build]` or `[meta]` section now
- new field ~~`app_name`~~ `[debug] name` — string without spaces and special symbols; instead of `name` and `executable`
- new field ~~`app_title`~~ `[meta] title` — any string; instead of `title`
- only ~~`app_name`~~ `[debug] name` is required now; default value for `version` is `1.0.0`
- ~~`app_name`~~ `[debug] name` validation; supports alphanumerical characters, dash and underscore
- ~~`version`~~ `[meta] version` validation; supports semver triple 
- hides `revision` field from the user
- `build` is `[build] script` now
also see https://github.com/socketsupply/socket/pull/124#issuecomment-1408740946
fixes #83
> config: cleanup

- .gitignore
- bin/install.ps1
- src/cli/cli.cc
bin\install.ps1 wasn't copying libuv src files
(Caused silent crash on copy files)
Note we currently require
bin\install.ps1 --uv 1.x
until 1.44.5 can be set as the default option.
Also resolved android command line tool path issues for windows, this relies on ANDROID_HOME being set. Also resolved --host option not being a valid argument
> android: Resolve windows build issues

- test/build.js
When altering the file:/// url, in Windows it includes the drive letter. e.g. file:///C:/. Make sure to do a regex match to catch any drive letter.
> windows: fix url file pathing

- package.json
- test/package.json
```
'.' is not recognized as an internal or external command,
```
We have 3 options:
1. Tell user to run ``npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"``, not great
2. Prefix all scripts with ``bash`` eg ``"test:desktop": "bash ./scripts/test-desktop.sh"`` - This doesn't work, ``PATH`` seems to be lost and ``ssc.exe`` can't be found
3. Prefix all scripts with ``sh`` eg ``"test:desktop": "sh ./scripts/test-desktop.sh",`` - This works on mac and windows
I have elected to go with 3.
Also updated ``standard`` call so that global install isn't required, user will now be prompted to install by ``npx``:
```
> npx standard .
Need to install the following packages:
standard@17.0.0
Ok to proceed? (y)
```
> ``./scripts-desktop.sh`` invalid syntax on win32.

- api/dgram.js
- api/ipc.js
- bin/install.ps1
- src/core/core.cc
- src/ipc/bridge.cc
- src/ipc/ipc.hh
- src/window/win.cc
- test/build.js
- test/src/dgram.js
- test/src/ipc.js
All the necessary changes to get `ipc:` schemes working on Windows. The test runner now runs to completion. Still has errors, but at least runs successfully without hanging.
> windows ipc: scheme support

- api/fs/handle.js
- src/core/runtime-preload.hh
- src/desktop/main.cc
- src/window/win.cc
- test/scripts/test-desktop.js
- test/src/fs/flags.js
- test/src/fs/index.js
- test/src/fs/promises.js
- test/src/ipc.js
- test/src/os.js
- test/src/path.js
- test/src/process.js
I'm not proud of how backslashes are escaped. All tests, except the runtime tests, are now passing.
I also believe there's a memory leak somewhere. The test runner requires > 900MB memory to execute. That doesn't sound right.
> Fix Windows tests

- src/ipc/bridge.cc
- src/window/linux.cc
The gtk library allocates resources when called. They need to be manually free'd or they'll leak all over like an over excited chihuahua.
The call to g_object_unref() is another way to free an allocation of a GObject. Since GTK has an internal reference counter (see https://discourse.gnome.org/t/when-should-i-use-g-object-unref/3834/2)
valgrind output for fs tests before fix:
definitely lost: 1,004,645,382 bytes in 19,428 blocks
indirectly lost: 941,726,112 bytes in 59,030 blocks
possibly lost: 493,737,863 bytes in 1,977 blocks
still reachable: 6,775,064 bytes in 36,079 blocks
and after tests:
definitely lost: 2,825 bytes in 38 blocks
indirectly lost: 11,461 bytes in 426 blocks
possibly lost: 67,146 bytes in 393 blocks
still reachable: 3,957,412 bytes in 36,028 blocks
> linux: free resources created by gtk

- src/app/app.cc
- src/app/app.hh
- src/cli/cli.cc
- src/common.hh
- src/desktop/main.cc
- src/process/process.hh
- src/process/win.cc
- src/window/win.cc
windows: disable extra console
1. Added additional code to win.cc to get tests to write to console
(These are probably in the wrong place, let me know if this can be improved)
3. modified cli to use SSC::Process when launching app, so std pipes can be captured and output
4. console can be reenabled using --w32-console
> Windows console fix

- test/src/dns.js
Random failures (`EAI_AGAIN`) on Android and Windows from cloudflare.com. I tried github.com, but I also get random failures. Maybe we should think about handling this in the test (retries?)
> fix(test/src/dns.js): drop cloudflare.com

- src/desktop/main.cc
- src/process/unix.cc
- src/process/win.cc
- src/window/win.cc
1. Introduce SSC::Process->killed flag to prevent illegal access exception
(object was being deleted before wait thread completed)
2. Resolve exitCode -> int conversion issue:
If exitCode == 1 in previous code, (int)exitCode == 0, not good.
Note that this is basically a cross platform issue, as Win32 `GetProcessExitCode()` sets a DWORD (uint), while POSIX like `wait_pid` sets an int_32_t (currently on macos).
> windows ci/test: Resolve process status issues

- api/os.js
- test/src/fs/index.js
- test/src/os.js
Using ?? an empty string can be returned. So instead use ||.
Also add a test to make sure the tmpdir() path length > 0.
> os: check tmpdir paths using ||

- api/bluetooth.js
- api/bootstrap.js
- api/dgram.js
- api/diagnostics.js
- api/diagnostics/channels.js
- api/diagnostics/index.js
- api/diagnostics/metric.js
- api/diagnostics/window.js
- api/dns/index.js
- api/dns/promises.js
- api/errors.js
- api/fs/fds.js
- api/fs/handle.js
- api/gc.js
- api/ipc.js
- api/os.js
- api/process.js
- api/util.js
- src/app/app.cc
- src/core/core.cc
- src/core/core.hh
- src/core/diagnostics.cc
- src/ipc/bridge.cc
- test/src/diagnostics.js
- test/src/diagnostics/channels.js
- test/src/diagnostics/window.js
- test/src/frontend/index.html
- test/src/index.js
- test/src/os.js
- test/src/test-context.js
This pull request introduces an initial _Diagnostics API_ for usable in user space and also suitable for retrieving real time information about the usage of various API modules.
**listening for UDP sockets created and counting bytes of sent/received network traffic:**
```js
import diagnostics from 'socket:diagnostics'
const group = diagnostics.channels.group('udp')
group.subscribe('socket', (message) => {
const { socket } = message // `socket` is an instance of `dgram.Socket`
})
let bytesReceived = 0
group.subscribe('message', (message) => {
const { buffer } = message
bytesReceived += buffer.length
})
let bytesWritten = 0
group.subscribe('send', (message) => {
const { buffer } = message
bytesWritten += buffer.length
})
```
**tracking requestAnimationFrame rate:**
```js
import diagnostics …
```
> Diagnostics API

- src/cli/cli.cc
this makes `ssc build -r dir` work (currently only `ssc build -r ./dir` works)
absolute paths still work after this change
> cli: fix path

- src/window/linux.cc
There is a case when `Window::getScreenSize()` returns `ScreenSize { 0, 0 }` when `Window#0` hasn't been created yet.
> Fix 'Window::getScreenSize()' on Linux

- src/cli/cli.cc
- src/desktop/main.cc
- src/process/process.hh
We were no longer handling signals with the move to `SSC::Process` from `SSC::exec`. This pull request introduces a signal handler.
> Handle signals in 'ssc(1)' to shutdown child app process

- api/crypto.js
- api/events.js
- api/external/libsodium/index.js
- api/util.js
- bin/publish-npm-modules.sh
- Assigns `libsodium` export to `crypto.sodium` export 
- Falls back to `sodium.randombytes_buf` in `crypto.getRandomValues`
- Exports `CustomEvent` in `socket:events` for usage in platforms that do not support it globally (node)
- Allow `encoding` to be given in `util.toBuffer()` where `Buffer.from()` is used
- Use `value` as `this` value when calling custom inspect (`Symbol.for('socket.util.inspect.custom')`)
- Introduce `compareBuffers()` for comparing `all `TypedArray` types, including `Buffer`
- Support `--link` for `publish-npm-modules.sh` which globally links the built node modules, instead of publishing  them (this makes it easier to develop against: `npm link @socketsupply/socket` just works)
> Various fixes

- bin/publish-npm-modules.sh
- src/cli/cli.cc
- src/common.hh
We were not handling debug output to the `OSLogStore`. This properly handles debug logs for a macos app and queries them in the `ssc` cli
> Fix debug logs on macOS

- .github/workflows/ci.yml
- bin/build-runtime-library.sh
- bin/cflags.sh
- bin/install.ps1
- bin/install.sh
- bin/ldflags.sh
- src/cli/cli.cc
- src/ipc/bridge.cc
- src/ipc/ipc.hh
- src/window/win.cc
- src/window/window.hh
- test/build.js
- test/src/frontend/index.html
Win32 socket: scheme is partially implemented, I had to resolve the below issue first.
install.sh: fix Win32 debug
Problem:
When building libuv and socket-runtime with debug enabled, our apps crash when 
using ifstream (readFile):
Debug Assertion Failed. Expression: (_osfile(fh) & fopen)
This build issue also interferred with debugging in Visual Studio.
This occured because by default the clang incorrectly links to the non 
threaded, production version of C runtime .lib (libcrt)
After taking the nessary steps to manually link to the correct lib 
(Including adding preprocessor definitions for /MT[d]),
ssc and apps would not link, therefore:
Solution:
This commit splits debug and release build artifacts:
d is set if $DEBUG and $host == Win32
*.o files are now named *$d.o
Libs are copied to …
> Windows socket scheme + Win32 debug build fix

- api/dgram.js
- api/diagnostics/window.js
- api/events.js
- api/hooks.js
- api/internal/globals.js
- api/internal/init.js
- api/internal/worker.js
- api/ipc.js
- api/worker.js
- src/android/bridge.cc
- src/android/bridge.kt
- src/android/main.kt
- src/android/window.kt
- src/ipc/bridge.cc
Given enough concurrent load, the UI thread locks up. This PR introduces concurrency control and moves route processing to a thread to prevent request interception from deadlocking or the UI thread from blocking
> Fix Android threading

- src/cli/cli.cc
- src/cli/templates.hh
This helps to wrap the existing application into Socket Runtime
> Add --config option to the ssc init

- bin/android-functions.sh
- bin/publish-npm-modules.sh
- src/cli/cli.cc
- src/cli/templates.hh
copying the the prebuilt libraries to `jniLibs` resulted in them being removed subsequently when `ndk-build` was called with `NDK_LIBS_OUT=<...>/jniLibs`. This change copies the prebuilts to a `libs/` directory and refers to them that way in the `Android.mk` file
> copy prebuilts to 'libs/' for JIT compile into 'jniLibs'

- api/crypto.js
heya,
I noticed this race when using `api/crypto.js` from node.
```js
import { getRandomValues } from './api/crypto.js'
console.error(getRandomValues(new Uint8Array(8)))
```
```js
Missing implementation for window.crypto.getRandomValues()
null
```
I think it's not triggered in the test suite because it executes on the next tick 🤔
> fix race condition when loading node:crypto

- src/cli/cli.cc
I'm not sure if this is the best solution, but it gets the issue on the agenda.
ssc --version works on win32.
`SSC::VERSION_FULL_STRING` is definitely being set, not sure why it doesn't work in the heap declaration.
before:
ssc -h
ssc v
after:
ssc -h
ssc v0.1.0 (a96824cc)
> cli.c: Fix  ssc -help shows empty version in win32

- bin/functions.sh
- bin/version-npm-modules.sh
Resolves error:
./bin/version-npm-modules.sh: line 23: cd: /c/socket/npm/packages/@socketsupply/socket-mingw64_nt-10.0-x64: No such file or directory
lower() was implemented in android-fte and should be merged soon.
> version-npm-modules: win32/mingw support

- bin/install.sh
- bin/publish-npm-modules.sh
- src/cli/cli.cc
- src/cli/templates.hh
- src/common.hh
I found myself often trying to log various environment variables related to `ssc`. This PR introduces a `ssc env` command that outputs `<key>=<value>` environment variable pairs, suitable for usage in a shell environment:
```sh
$ ssc env
ANDROID_HOME=/Users/werle/Library/Android/sdk
GRADLE_HOME=/Users/werle/.sdkman/candidates/gradle/current
HOME=/Users/werle
JAVA_HOME=/Users/werle/.sdkman/candidates/java/current
LANG=en_US
LC_ALL=en_US.UTF-8
LC_CTYPE=UTF-8
LC_TERMINAL=iTerm2
LC_TERMINAL_VERSION=3.4.18
PREFIX=/Users/werle/repos/socketsupply/socket/build/npm/darwin/packages/@socketsupply/socket-darwin-arm64
PWD=/Users/werle
SHELL=/bin/bash
SOCKET_HOME=/Users/werle/repos/socketsupply/socket/build/npm/darwin/packages/@socketsupply/socket-darwin-arm64/ …
```
> Introduce 'ssc env'

- api/test/context.js
- api/test/index.js
- src/cli/cli.cc
- src/common.hh
- test/src/index.js
I found myself reusing the `text-context.js` file in other socket modules. This moves it into the standard library making it reusable in other projects/modules.
> Introduce a reusable text context

- src/cli/templates.hh
it's currently not visible on iPhone, because it's under the notch
> fix(src/cli/template.hh): center text in the html template vertically

- bin/android-functions.sh
- bin/clean.sh
- bin/functions.sh
- bin/install.sh
- npm/bin/ssc.js
- npm/src/index.js
- src/cli/cli.cc
- src/cli/templates.hh
- src/core/udp.cc
- src/ipc/bridge.cc
- test/scripts/shell.sh
- test/scripts/test-android-emulator.sh
This PR improves `ssc setup` in various ways including the output during the FTE and setup to give users more feedback about what is going on aligning the output style with the rest of build scripts.
> ssc-setup fixes

- bin/functions.sh
- npm/src/index.js
Running `ssc --version` had a bunch of unrelated output:
```
ok - ANDROID_HOME, JAVA_HOME, and GRADLE_HOME search paths configured.
ok - Found JAVA_HOME (/opt/homebrew/Cellar/openjdk/19.0.2/libexec/openjdk.jdk/Contents/Home)
ok - Found GRADLE_HOME (/Users/werle/.gradle/wrapper/dists/gradle-7.6-bin/9l9tetv7ltxvx3i8an4pb86ye/gradle-7.6)
ok - Found ANDROID_HOME (/Users/werle/Library/Android/sdk)
ok - Found sdkmanager (cmdline-tools/latest/bin/sdkmanager)
[=======================================] 100% Computing updates...
```
This PR makes FTE output quiet for most commands that don't need the output
> FTE should be quiet for regular commands

- bin/functions.sh
- npm/src/index.js
linux fte: inform user why `sudo` by outputting commands
`log_and_run` is similar to `quiet`, but it always outputs the command string.
Fixed `write_log` to better support multiple arguments (It would only output "sudo" with the `log_and_run` calls otherwise)
run android setup from ssc.js:
This can be done now due to changes from @jwerle
> linux fte improvements

- bin/build-runtime-library.sh
- bin/functions.sh
- bin/install.sh
Also use VERSION.txt mtime
Resolves publish-npm-modules.sh error: "Repo $REPO_VERSION and $SOCKET_HOME/bin/ssc $BUILD_VERSION don't match."
This is a quick way of handling this without determining the actual .hh dependency chain within each .cc file
> install.sh: use .hh mtimes to invalidate .o

- bin/android-functions.sh
Resolves issue where new return code from Android deps install prompt is incorrectly executed instead of being tested.
> android fte: fix `if $rc` syntax 

- api/README.md
- api/config.md
- bin/generate-docs.js
- src/cli/cli.cc
- src/cli/templates.hh
Undocumented stuff from config:
> generate socket.ini documentation

- .github/workflows/ci.yml
- package.json
Fail CI early when linting doesn't pass or when git working directory is not clean after generating docs. This can save resources on building ssc on the platforms.
> chore(ci): fail early

- .github/workflows/ci.yml
- bin/generate-typescript-typings.sh
- package.json
now the `Lint` CI job correctly checks linting and ensures that TS definitions and docs are generated against the latest version.
To generate all the necessary files do `npm run gen` and push them to pass the linting
> CI and .d.ts gen fixes

- bin/build-runtime-library.sh
- bin/cflags.sh
- bin/install.sh
- src/cli/cli.cc
- src/cli/templates.hh
Fixes silent crash when testing apps on iPhoneSimulator running on Mac M1 or later
Fixes https://github.com/socketsupply/socket/issues/374
> arm64-iPhoneSimulator: Enable support

- api/config.md
- src/cli/templates.hh
This is an internal value used to create a setting in debug. Fixes 'false' appearing in AndroidManifest.xml (Invalid XML)
> android: allow_cleartext: Remove from ini.

- src/window/linux.cc
https://github.com/socketsupply/socket/issues/363
> Set monitor default geometry on Linux

- .github/workflows/ci.yml
- bin/android-functions.sh
- bin/functions.sh
- src/cli/cli.cc
- test/scripts/bootstrap-android-emulator.sh
- test/scripts/poll-adb-logcat.sh
- test/scripts/test-android-emulator.sh
+ switch to using test-android-emulator
This allows us to test outside CI more reliably, rather than relying
on github actions
+  Implemented timeout / watchdog setup to handle app failures
that aren't caught by main adb loop in poll-adb-logcat.sh
+ macos android ci: Don't use avd cache
"The cache became corrupted"
The cache doesn't seem any faster than just firing up a clean AVD image
+ fix jniLibs not building when flagRunUserBuildOnly set (CI wasn't testing this before, libsocket-runtime.so wasn't being deployed with the app)
+ implement app start timeout and error output to catch failed app starts, which in turn prevents CI hanging because it would never receive a signal from webview js
+ dont search /Applications for java, this is extremely slow under CI
+ require exact java version …
> Macos (Android) CI: Incorporate Android FTE

- api/crypto.js
does this make sense to clean up nodejs support for webcrypto?
> crypto: simplify nodejs webcrypto

- src/cli/cli.cc
I was deprecated for a few versions already and printed a warning message, but I think no users were using after the latest release it and it's safe to remove it.
> refactor(src/cli/cli.cc): remove [build] input completely

- src/cli/cli.cc
* android build cwd: don't run from build folder
(where possible)
Partially resolves file lock issue on windows where folders are locked
while processes are using them as pwd
Note that gradle has to run from build folder, but this change still
results in less process to kill.
* android: improve static lib dx
Always copy libs, even if jniLibs exists, this may have been an issue and the performance detriment is negligable
ERROR out if static libs don't exist in SOCKET_HOME
> Android improvements

- src/common.hh
eg
```ini
build = "src;src2=dst"
```
Previously this would be handled as a single src location, src2 would be ignored.
> parseINI: support comments in quoted values

- src/cli/cli.cc
- src/common.hh
Windows CreateProcess() won't work if the script has an extension other than exe (say .cmd or .bat) cmd.exe can handle this translation
Also change stdWrite, remove duplicate output on win32, WriteConsoleA() doesn't seem to be required now.
> cli.cc(fix): resolve build_script issue on win32

- .github/workflows/ci.yml
- api/README.md
- api/hooks.js
- api/index.d.ts
- api/internal/init.js
- api/test/context.js
- test/src/hooks.js
- test/src/index.js
This PR also introduces new tests to cover the API which should look like:
```js
import hooks from 'socket:hooks'
hooks.onLoad(() => {
// called when the runtime context has loaded,
// but not ready or initialized
})
hooks.onReady(() => {
// called when the runtime is ready, but not initialized
})
hooks.onInit(() => {
// called when the runtime is initialized
})
hooks.onError((event) => {
// called when 'error', 'messageerror', and 'unhandledrejection' error
// events are dispatched on the global object
})
hooks.onData((event) => {
// called when 'data' events are dispatched on the global object
})
hooks.onMessage((event) => {
// called when 'message' events are dispatched on the global object
})
hooks.onOnline((event) => {
// called when 'online' events are dispatched on the global …
```
> Rework hooks API internals

- bin/ci_version_check.ps1
- bin/ci_version_check.sh
- bin/install.sh
- src/cli/cli.cc
- src/cli/templates.hh
> feat(src/cli/cli.cc): print installation path

- .github/workflows/ci.yml
- bin/ci_changes_check.sh
- bin/generate-docs.js
This will make links correct for both `master` and release branches.
When version from `VERSION.txt` doesn't exist on remote yet, we should generate docs for that version so links will point to the correct version when we publish a new version before we tag and merge it.
> Pin API docs version

- src/ios/main.mm
https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/
> fix inspect

- src/window/win.cc
Set focus on webview control
Only disable keyboard shortcuts when !isDebugEnabled
Implement showInspector()
> webview2 improvements:

- api/util.js
use local stack trace rather than the one generated by eval driven ipc result
> ipc errors: include original callsite in stack

- src/cli/cli.cc
Issue occured if a [build] script was configured in socket.ini
Don't cd into target path, just call build script with target path as arg
Fixes https://github.com/socketsupply/socket/issues/475
> cli: fix ./gradlew: not found

- src/cli/cli.cc
cli: android: fail immediately if adb fails to install to device
Don't wait for emulator to boot.
+ improve error messages.
> Android app start fix

- api/README.md
- package.json
Typescript 5.1.0 has some changes that lead to these errors. We have to figure out how to suppress them or how to change the code to pass checks, but for now we can just use v5.0.5
```
api/diagnostics/index.js:7:10 - error TS6232: Declaration augments declaration in another file. This cannot be serialized.
7 export { channels, window }
~~~~~~~~
api/diagnostics.js:5:1
5 import * as exports from './diagnostics.js'
~~~~~~
This is the declaration being augmented. Consider moving the augmenting declaration into the same file.
api/diagnostics/index.js:7:20 - error TS6232: Declaration augments declaration in another file. This cannot be serialized.
7 export { channels, window }
~~~~~~
api/diagnostics.js:5:1
5 import * as exports from './diagnostics.js'
~~~~~~
This is the declaration being …
```
> Pin TS to version 5.0.4

- bin/generate-docs.js
use VERSION for docs links if either the VERSION is a current tag or VERSION tag doesn't exist on remote yet. Otherwise use master branch
> fix(CI): improve git tag chech for docs generation

- src/cli/cli.cc
init makefileContext["__android_native_extensions_context"] with empty value, prevent {{__android_native_extensions_context}} in final output if there are no extensions
> native ext(fix): prevent template tag on no ext's

- src/cli/templates.hh
this removes an extra step all the time I want wrap an existing web app
> chore(config): add redirection to index.html by default

- src/desktop/main.cc
ref https://github.com/socketsupply/socket/issues/431
> fix(desktop/main.cc): check for invalid values for the application window sizes

- src/android/window.cc
- src/cli/cli.cc
- src/common.hh
- src/desktop/main.cc
- src/ios/main.mm
- src/window/window.hh
> use 'hasEnv' for env value checks

- .github/workflows/ci.yml
- package.json
TypeScript doesn't follow SemVer and it can introduce breaking changes in the minor versions.
> chore(deps): TypeScript semver

- api/index.d.ts
- api/test/context.js
- api/test/index.js
- test/src/index.js
> Autoinitialize test context

- src/cli/cli.cc
- src/common.hh
- src/desktop/main.cc
- src/init.cc
Mobile builds were broken by #564 
This also re-uses `[build] headless` from the baked-in config and simplifies build significantly.
> Fix mobile builds

- bin/functions.sh
Suggested Fixes #563.
This will also ignore binaries that throw errors on `--version`.
**Explanation**:
`bin_version="#$("$clang" --version|head -n1)#$clang"` adds a prefix `#` to the `$bin_version` lines.
`sed '/^##/d'` removes any line without a version.
The function then proceeds by setting `$CXX` to point to the latest version of the `clang++` binary.
> fix(determine_cxx): ignore clang binaries that don't have `--version`

- src/core/runtime-preload.hh
This will give user space a chance to declare an [ImportMap](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) before any scripts are loaded, include `socket:internal/init`
> import 'socket:internal/init' when interactive

- src/window/win.cc
Sometimes, a mime type cannot be determined from common extensions
> Handle various common mime types on Windows

- src/cli/cli.cc
This will be useful for async processes, like file watchers, or HTTP servers
> refactor(src/cli/cli.cc): allow async build after script

- api/config.md
- src/cli/cli.cc
- src/cli/templates.hh
> Make `ssc build` fail early when `[meta] build_identifier` is not provided

- src/core/javascript.cc
- Use JSON encoding of the value string to allow for backtick characters.
- Escape any escape characters to account for string interpolation.
> fix: `getEmitToRenderProcessJavaScript` value encoding

- api/CONFIG.md
- src/cli/cli.cc
- src/cli/templates.hh
This is important so `vite` or `create-react-app` build step (`[build] script = "npm run build"`) can create a build and then `[build] copy = "<dist>"` will move the built app to the Socket app resources
> fix(scr/cli/cli.cc): make `[build] script` phase run before `[build] copy` phase

- src/cli/cli.cc
If a path in `build.extensions` does not exist or an extension's `socket.ini` has no source files declared, a warning will be logged.
> fix(cli): warn when extension sources are not found

- bin/functions.sh
This skips the Android download prompt when running `NO_ANDROID=1 ssc build`
> feat(cli): respect NO_ANDROID=1 in `ssc build`

- npm/packages/@socketsupply/socket-node/index.js
This fix encodes any `\n` characters for the ipc://stderr message.
The `String(…)` call is not strictly necessary, but keeps tsc satisfied.
> fix: encode uncaught exception before writing to ipc

- src/desktop/main.cc
This PR is useful when running `./path/to/MyApp.app/Contents/MacOS/MyApp` from the terminal, as it lets you view the backend logs without opening up Console.app (which wasn't possible before this PR) or, worse, saving to a logfile that you tail manually. The reason I added Console.app support anyway is for viewing logs when running the app via `open ./path/to/MyApp.app` or clicking the app icon from the Dock.
Before this PR, saving to a logfile was your only choice.
- feat: write backend logs to stdout/stderr
- feat(mac): forward backend logs to Console.app
- fix(backend): move stdout/stderr handling off of main thread
*This also moves IPC message parsing off the main thread.*
> feat: write backend logs to std::cout/std::cerr and forward them to Console.app on macOS

- .npmrc
- pnpm-workspace.yaml
- Users can decide for themselves between npm or pnpm
- Disabled lockfile generation
- pnpm users don't have to set up the `pnpm-workspace.yaml` file themselves (which tells pnpm to install `@socketsupply/socket-node` dependencies when `pnpm install` is used in the root directory)
- pnpm has a [changesets guide](https://pnpm.io/using-changesets) with a Github CI action that automatically releases. Adding changesets in the future will also let you more easily align the package versions of `@socketsupply/socket` and `@socketsupply/socket-node` (see [Fixed Packages](https://github.com/changesets/changesets/blob/main/docs/fixed-packages.md) in their docs)
> chore: use pnpm workspaces

- src/cli/cli.cc
This makes it easier to debug an extension's `configure.script` when it fails.
> fix(cli): log `configure.script` output when exitCode is non-zero

- bin/publish-npm-modules.sh
When running `bin/publish-npm-modules.sh --link` repeatedly, the `npm link` can fail if you don't use `--force`.
> fix: use --force with npm link

- include/socket/extension.h
- src/extension/ipc.cc
```c++
#include <socket/extension.h>
bool my_extension_function(sapi_ipc_result_t* result) {
// Do some work...
if (error_occurred) {
const char* error_message = "An error occurred";
return sapi_ipc_reply_with_error(result, error_message);
} else {
// Send the result...
return sapi_ipc_reply(result);
}
}
```
> feat(extension): add `sapi_ipc_reply_with_error` function

- src/cli/cli.cc
This prevents a useless warning:
```
• WARN build_extensions_node-zeromq_build_script is not a directory, ignoring: /Users/alec/dev/socket-node-zeromq/src/extension.cc +312ms
```
> fix(cli): skip build.script when looking for extension sources

- api/window.js
The value is expected by socket-node to be valid JSON:
https://github.com/socketsupply/socket/blob/7bcf246bbaf96d93447df41e3c851d36ec3fd65b/npm/packages/@socketsupply/socket-node/index.js#L123
> fix(ipc): stringify the value passed to `process.write`

- api/ipc.js
I've seen instances where `value=undefined` was included, which isn't a huge deal, but also not intended behavior.
> fix(ipc): omit `value` parameter if value is undefined

- src/cli/cli.cc
Here's an example `socket.ini` for a native extension:
```ini
[meta]
name = "foo"
type = "extension"
[extension]
sources[] = ./src/extension.cc
[extension.compiler]
flags[] = -I./include
[extension.linker]
flags[] = $(pkg-config libsodium --libs)
flags[] = -L$PWD/node_modules/zeromq/build/libzmq/lib
flags[] = -lzmq
```
- Only values of `flags[]` are evaluated by this PR.
- Each value is searched for `./` and `../` paths to be resolved relative to the extension's root directory.
- Each value is searched for `$(…)` and replaces it with its execution result (trimmed and with `\n` replaced by spaces).
- Each value is searched for `$abc_123`-like substrings and replaces them with matching environment variables. Not sure if this is super necessary (the `exec` call when compiling/linking might …
> feat(cli): allow subcommands, variables, and relative paths in extension compiler/linker flags

- include/socket/extension.h
- src/core/core.hh
- src/extension/ipc.cc
- src/ipc/bridge.cc
- src/ipc/ipc.cc
- src/ipc/ipc.hh
- src/window/win.cc
- Before calling sapi_ipc_send_chunk, you must first set the Transfer-Encoding header to `chunked` and then call sapi_ipc_reply.
- When using sapi_ipc_send_chunk, the frontend should use XMLHttpRequest. Currently, the Fetch API does not support response streaming in WebKit.
- Before calling sapi_ipc_send_event, you must first set the Content-Type header to `text/event-stream` and then call sapi_ipc_reply.
- When using sapi_ipc_send_event, the frontend should use EventSource.
> feat(extension): add `sapi_ipc_send_chunk` and `sapi_ipc_send_event`

- api/README.md
- api/application.js
The validation logic in `application.js` was too strict, as the proper way to declare an unbound menu item (i.e. you must click the item, no key binding exists) is by omitting a `:` from the line.
> fix: setSystemMenu JS validation

- src/extension/context.cc
- src/extension/extension.cc
- src/extension/extension.hh
- src/extension/ipc.cc
- Correctly retain the context when:
- Transfer-Encoding header is set to `chunked`
- Content-Type header is set to `text/event-stream`
- Add debug log for incorrect use (failure to set expected header)
> Some fixes to `send_event` and `send_chunk` extension APIs

- src/cli/cli.cc
Enable system push notifications on iOS/macOS with correct entitlements:
- [`com.apple.developer.location.push`](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_location_push?language=objc)
- [`com.apple.developer.usernotifications.filtering`](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_usernotifications_filtering?language=objc)
These SHOULD be enabled with the `[permissions] allow_push_notifications` permission, which is `false` by default. These permissions require entitlement permissions from Apple.
> fix(cli.cc): fix push notification permission

- npm/packages/@socketsupply/socket-node/API.md
- npm/packages/@socketsupply/socket-node/index.js
It seemed odd to need to handle errors as a promise result, rather than through a catch callback.
> fix(socket-node): avoid resolving `send` promise with Error object

- api/README.md
- api/path/path.js
- test/src/path.js
Closes https://github.com/socketsupply/socket/issues/706
Also fixes and re-enables some disabled tests.
> Fix missing absolute path separator

- include/socket/extension.h
- src/ipc/bridge.cc
**Status:** Seems to work
macOS does not allow `didReceiveResponse` or `didReceiveData` calls if a URL scheme task is cancelled.
> fix(mac): avoid "This task has already been stopped" exceptions

- api/README.md
- api/fs/dir.js
- api/fs/handle.js
- api/fs/index.js
- api/fs/promises.js
- api/fs/stream.js
- api/fs/watcher.js
- api/index.d.ts
- src/core/core.cc
- src/core/core.hh
- src/core/fs.cc
- src/core/preload.cc
- src/ipc/bridge.cc
This PR introduces the `fs.watch()` and `fs.Watcher` APIs. It is implemented to give as much parity as possible with node's implementation.
`EventEmitter`:
```js
import process from 'socket:process'
import fs from 'socket:fs'
// watch resources directory
const watcher  = fs.watch(process.cwd())
watcher.on('change', (eventType, filename) => {
console.log(eventType) // 'change' or 'rename'
console.log(filename) // file name relative to `process.cwd()`
})
```
`AsyncIterator` (with `filename` encoding):
```js
import process from 'socket:process'
import fs from 'socket:fs/promises'
// output `filename` as `Buffer` instance
const events = fs.watch(process.cwd(), { encoding: 'buffer' })
for await (const event of events) {
console.log(event) // { eventType: 'change' | 'rename' , filename: <Buffer …
```
> Introduce 'fs.watch' and 'fs.Watcher'

- api/CLI.md
- src/cli/cli.cc
- src/cli/templates.hh
- src/core/preload.cc
Fixes:
- add `--port` and `--host` as valid flags
- remove `--stdin` (not implemented)
- remove flag duplicates from `build` command (those that are already in the `run`)
- fixes for help output and CLI.md
> fix(src/cli/cli.cc): fixes for build and run commands

- api/README.md
- api/fs/index.js
- api/fs/promises.js
- api/index.d.ts
- src/core/core.hh
- src/core/fs.cc
- src/ipc/bridge.cc
- test/scripts/test-desktop.js
- test/src/fs/index.js
- test/src/fs/promises.js
This adds a recursive option to mkdir. 
Closes https://github.com/socketsupply/socket/issues/714
> Add a recursive option to mkdir

- src/extension/ipc.cc
- src/ipc/bridge.cc
- src/ipc/ipc.cc
- src/ipc/ipc.hh
Since the message is copied, we need a pointer for `sapi_ipc_set_cancellation_handler` to work as expected.
Currently, only HTTP requests to `ipc://` addresses can have a cancellation handler set by an extension route (and only on macOS). But in the future, this could be added to other platforms or even other transport types.
> fix: use a `shared_ptr` for IPC HTTP request cancellation callback

- api/CONFIG.md
- src/cli/cli.cc
- src/cli/templates.hh
This is the simplest solution which fixes the #716. It doesn't pass any arguments as environment variables and just skips them until `[build] pass.build.arguments` is equal `true` explicitely
> Introduce '[build] build.forward_arguments'

- src/window/apple.mm
This adds support for shortcuts like `b + Alt + Control + Meta` on macOS `setSystemMenu` items.
> fix(setSystemMenu): support multiple modifiers on macOS

- src/window/apple.mm
Handle cases where there are multiple empty lines before a menu begins.
This affects macOS only.
> fix(setSystemMenu): handle empty lines correctly

- api/index.d.ts
- api/internal/permissions.js
- api/notification.js
- src/ipc/bridge.cc
This PR improves the `Notification` API and the `Notification.requestPermission` API by returning the correct permission value, defaulting to "alert" style notifications on macOS/iOS. User's can control this setting in the operating system settings app on macOS/iOS.
> Improve 'Notification' api

- api/index.d.ts
- api/path.js
- api/path/index.js
- api/path/well-known.js
- src/android/bridge.kt
- src/ipc/bridge.cc
This PR introduces well known path constants for use with path resolution or the `socket:fs` module.
It includes constants for the following:
- `path.DOWNLOADS` A path to the user's or app container `Downloads/` folder
- `path.DOCUMENTS` A path to the user's or app container `Documents/` folder
- `path.PICTURES` A path to the user's or app container `Pictures/` folder
- `path.DESKTOP` A path to the user's or app container `Desktop/` folder
- `path.VIDEOS` A path to the user's or app container `Videos/` folder
- `path.MUSIC` A path to the user's or app container `Music` folder
> feat(api/path): introduce well known path constants

- api/internal/permissions.js
When os.platform was returning iOS, it wasn't being treated as an apple device.
> Fix os.platform bug

- src/cli/cli.cc
make `<path>` work, take name from path when possible
@jwerle probably same changes needed in the CLI refactor branch.
- Project name will be the last child directory name (current directory name if `ssc init` is run without a path)
- `--name` have preference over the one from the path
> update ssc init

- test/src/fs/index.js
We can merge this one after 0.5 release if necessary. It makes macOS CI more reliable
> test(test/src/fs/index.js): simplify fs.writeFile test

- test/src/application.js
> chore(test/src/application.js): increase timeout for backend.open({ force: true })) to send event

- src/cli/cli.cc
`ssc build -h` states that watch should run with either `--watch` or `-w`:
```
-w, --watch                          watch for changes to rerun build step
```
`cli.cc`, however, sets the shorthand to `-W`.
This PR addresses this.
> Fix build watch cli shorthand (`-w`)

- api/README.md
- api/path/path.js
Static initialization blocks are only supported since Safari 16.4, so users on macOS Ventura will get an error
> fix(api/path/path.js): avoid static initializer

- npm/packages/@socketsupply/socket/package.json
This causes problems with things like loaders...
```
> /usr/bin/node --experimental-loader @socketsupply/socket/node-esm-loader.js introducer.js
(node:864627) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:490
ErrorCaptureStackTrace(err);
^
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './node-esm-loader.js' is not defined by "exports" in /opt/streamrelay/node_modules/@socketsupply/socket/package.json imported from /opt/streamrelay/
at new NodeError (node:internal/errors:399:5)
at exportsNotFound (node:internal/modules/esm/resolve:266:10)
at packageExportsResolve (node:internal/modules/esm/resolve:602:9)
at packageResolve …
```
> Remove narrow exports specifier

- api/stream-relay/cache.js
- api/stream-relay/packets.js
handles case where bytes are malformed according to the packet spec or when the packet is an unexpected length (do not read past buf-len, etc)
> harden protocol decode

- api/url/index.js
> fix(api/url/index.js): fix how URL origin is determined

- api/index.d.ts
- api/module.js
- api/vm.js
- api/vm/index.html
- api/vm/init.js
- api/vm/worker.js
- api/vm/world.html
- api/vm/world.js
- test/src/ipc.js
This pull request introduces the `socket:vm` module. It is similar in API surface to the `node:vm` module, but all exported functions are async as the internal semantics, context execution, and JavaScript environment are completely different.
```js
import vm from 'socket:vm'
const result = await vm.runInContext('1 + 2 + 3')
console.log(result) // 6
```
Users of this module can supply a custom context object that is available in the `globalThis` scope of the execution context. Values that can be passed to a script virtual machine are the same that can be passed to a worker. We introduce a "reference proxy" that can be used to reference object instances in a VM to the caller. Functions are automatically detected, referenced, and made available as a proxy call.
```js
import vm from …
```
> Introduce VM module

- src/core/javascript.cc
- src/core/preload.cc
- src/window/win.cc
This PR introduces support for creating platform hotkey bindings on desktop environments only.
```js
import { hotkey } from 'socket:window'
await hotkey.bind('ctrl + k')
hotkey.addEventListener('hotkey', (event) => {
console.log(event.id, event.sequence) // 1025, ['ctrl', 'k']
})
```
Hot key bindings only work when the application is focused. Supporting global hot keys involves working with `libx11` which we'd rather not do at the moment.
> Introduce platform hotkeys API

- npm/src/index.js
This PR fixes an issue that happens, at least on Windows, when the user has a space character in their Username.
The symptom:
```
> ssc init
node:internal/modules/cjs/loader:1147
throw err;
^
Error: Cannot find module 'C:\Users\Jan%20Starzak\AppData\Roaming\nvm\v20.11.1\node_modules\@socketsupply\socket\node_modules\@socketsupply\socket-win32-x64\bin\ssc-platform.js'
at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
at Module._load (node:internal/modules/cjs/loader:985:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
at node:internal/main/run_main_module:28:49 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
```
On Windows (but maybe on other platforms too), file URLs can contain spaces which will be encoded as %20. When treating …
> fix(npm index.js): convert file url to actual path

- src/cli/cli.cc
fix `replace` calls in cli to only match the extension at end of file paths
currently if you have a ".c", ".cc", ".m" in any directory names in your project working directory, then you are unable to compile an extension as all the ".c" etc will get replaced while the compile flags are being generated.
example:
"/src/github.com/chrisfarms/my-socket-app/extensions/something.c"
becomes
"/src/github.**oom**/chrisfarms/my-socket-app/extensions/something.o"
⚠️ this PR is against `next`
> cli: only replace file ext, not path

- api/fetch/index.js
- api/internal/init.js
* `Buffer.concat` expects either a Uint8Array or Buffer ... but the fetch ReadableStream passes in a plain ArrayBuffer ... this makes it unhappy ... so this wraps in the TypedArray before giving to concat
* URL passing during xhr open seems to fail for some URLs (blob urls?) ... url can be either a string or a URL, and there were no checks so this was exploding
I am attempting to get [three.js GLTFLoaders](https://threejs.org/docs/#examples/en/loaders/GLTFLoader) working, and running into the above issues.
I am NOT confident that either of these are the right thing to do.
Should Buffer.concat actually be fixed to support plain ArrayBuffers instead?
Why is there a silent catch around the URL parsing?
> resolve xhr issues loading from worker
